-
  name: execute a script
  hosts: all
  connection: local
  tasks:
    -
      name: copy file to the location
      copy:
        src: test.sh
        dest: /tmp
        mode: 0755
      delegate_to: localhost
      run_once: yes
    -
      name: execute the script
      script: /tmp/test.sh
      delegate_to: localhost
      
      
      
        
      
        
