-
  name: execute a script
  hosts: all
  connection: local
  tasks:
    -
      name: copy file to the location
      copy:
        src: /test.sh
        dest: /tmp/test.sh
        mode: 0644
        remote_src: yes
      delegate_to: localhost
      run_once: yes
    -
      name: execute the script
      shell: /tmp/test.sh
      delegate_to: localhost
      
      
      
        
      
        
