-
  name: execute a script
  hosts: 127.0.0.1
  connection: local
  tasks:
    -
      name:
      local_action:
        module: git
        repo: https://github.com/syellayi023/ansible
        dest: /tmp/test
        
        
      command: ./test.sh
     
     
    
      
      
      
        
      
        
