-
  name: execute a script
  hosts: 127.0.0.1
  connection: local
  tasks:
    -
      name: copy file to the location
      copy:
        src: ./test.sh
        dest: /tmp/test.sh
        mode: 0755
      delegate_to: localhost
      run_once: yes
    -
      name: execute the script
      shell: /tmp/test.sh
      delegate_to: localhost
      
      
      
        
      
        
